const USER_ROLES = {
    SUPERADMIN: 'SUPERADMIN',
    ADMIN: 'ADMIN',
    VALIDATOR: 'VALIDATOR',
    USER: 'USER'
};

const ALL_ROLES = [
    USER_ROLES.SUPERADMIN,
    USER_ROLES.ADMIN,
    USER_ROLES.VALIDATOR,
    USER_ROLES.USER
];

const USER_MANAGEMENT_ROLES = [
    USER_ROLES.SUPERADMIN
];

const BULK_EXECUTION_ROLES = [
    USER_ROLES.SUPERADMIN,
    USER_ROLES.ADMIN
];

const VALIDATION_ROLES = [
    USER_ROLES.SUPERADMIN,
    USER_ROLES.VALIDATOR
];

const PRIVILEGED_READ_ROLES = [
    USER_ROLES.SUPERADMIN,
    USER_ROLES.ADMIN,
    USER_ROLES.VALIDATOR
];

const VALIDATION_STATUS = {
    PENDING_VALIDATION: 'PENDING_VALIDATION',
    VALIDATED: 'VALIDATED',
    REJECTED: 'REJECTED'
};

const ALL_VALIDATION_STATUSES = [
    VALIDATION_STATUS.PENDING_VALIDATION,
    VALIDATION_STATUS.VALIDATED,
    VALIDATION_STATUS.REJECTED
];

module.exports = {
    USER_ROLES,
    ALL_ROLES,
    USER_MANAGEMENT_ROLES,
    BULK_EXECUTION_ROLES,
    VALIDATION_ROLES,
    PRIVILEGED_READ_ROLES,
    VALIDATION_STATUS,
    ALL_VALIDATION_STATUSES
};
